routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LinkController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['as' => 'link.'], function() {
    Route::get('/', [LinkController::class, 'create'])->name('create');
    Route::post('/', [LinkController::class, 'store'])->name('store');

    Route::get('/' . config('link.path') . '/{link:hash}', [LinkController::class, 'redirect'])->name('redirect');
});

app/Models/Link.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Link extends Model
{
    use HasFactory;

    /**
     * Создает короткую ссылку
     * @param string $url
     * @return string
     */
    public function createShort(string $url): string
    {
        // если уже существует короткая ссылка на этот url, возвращаем её (настройка зависит от config link.use.old_if_exists)
        if(config('link.use_old_if_link_exists') and $link = $this->checkExistShortLink($url)) {
            return $link;
        }

        $this->url = $url;
        $this->hash = $this->generateHash();
        $this->save();

        $link = $this->getLinkByHash($this->hash);
        return $link;
    }

    /**
     * Генерирует хэш для ссылки
     * @return string
     */
    private function generateHash(): string
    {
        $hash = md5(microtime() . date('ymdhis'));
        $hash = substr($hash, 0, config('link.length'));
        return $hash;
    }

    /**
     * Проверяем существование короткий ссылки для url, если существует, возвращает короткую ссылку
     * @param string $url
     * @return bool|string
     */
    private function checkExistShortLink(string $url): string
    {
        if($link = Link::where('url', $url)->first()) {
            return $this->getLinkByHash($link->hash);
        }

        return false;
    }

    /**
     * Возвращает полную короткую ссылку по хэшу
    */
    private function getLinkByHash(string $hash): string
    {
        return route('link.redirect', ['link' => $hash]);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/LinkController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Link;
use App\Http\Requests\LinkRequest;

class LinkController extends Controller
{
    /**
     * Форма создания короткой ссылки
     */
    public function create() {
        return view('link.form');
    }

    /**
     * Обработка формы
     */
    public function store(LinkRequest $request) {
        $link = new Link();
        $link = $link->createShort($request->url);

        return json_encode(['link' => $link]);
    }

    /**
     * Редирект по короткой ссылке
     */
    public function redirect(Link $link) {
        return redirect($link->url);
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>@yield('title')</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">
    </head>
    <body>
        <div class="content">
            @yield('content')
        </div>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        @yield('javascript')
    </body>
</html>

resources/views/link/form.blade.php
@extends('layouts.app')

@section('title', 'Create short link')

@section('content')
<div class="row justify-content-md-center">
    <div class="col-md-3 py-5 my-5 mx-6">
        <h4 class="mb-3">Create short link</h4>
        <div class="alert alert-danger hidden" id="error-alert" role="alert"></div>
        <div class="alert alert-success hidden" id="success-alert" role="alert">
            Your link is <a id="success-link"></a>
        </div>

        <form class="" action="{{ route('link.store') }}" id="link-form" method="POST">
            <div class="input-group py-2">
                  <label for="url" class="form-label">URL</label>
                  <div class="input-group mb-3">
                    <input type="text" name="url" required id="url" class="form-control" placeholder="https://google.com">
                    <div class="input-group-append">
                      <button class="btn btn-outline-secondary" type="button" id="form_btn">Create</button>
                    </div>
                  </div>
            </div>
            @csrf
        </form>
    </div>
</div>
@endsection

@section('javascript')
<script type="text/javascript">
$(document).ready(function() {
    $('#form_btn').click(function() {
        $('#error-alert').html('').hide();
        $('#success-alert').hide();

        var data = $('#link-form').serialize();

        $.ajax({
            type: 'POST',
            url: '{{ route('link.store') }}',
            data: data,
            dataType: 'json'
        }).done(function(response) {
            $('#success-link').attr({href: response.link}).html(response.link);
            $('#success-alert').show();
        }).fail(function(response) {
            var errors = response.responseJSON.errors;

            for(var error in errors) {
                $('#error-alert').append('<p>' + errors[error] + '</p>');
            }

            $('#error-alert').show();
        });
    });
});
</script>
@endsection